import path from "path"
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'
import basicSsl from '@vitejs/plugin-basic-ssl'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    basicSsl(),   // self-signed HTTPS — required for getUserMedia on LAN (non-localhost)
  ],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "./src"),
    },
  },
  server: {
    host: true,        // bind to 0.0.0.0 — accessible from phone on same Wi-Fi
    port: 5173,
    https: {},         // enable HTTPS (cert auto-generated by basicSsl plugin)
    proxy: {
      '/api': {
        target: 'http://localhost:3000',
        changeOrigin: true,
        secure: false,
      },
    },
  },
})
